Vivero/Inventory/urls.py
from django.urls import path
from . import views
from .views import Vista_subir_excel

urlpatterns = [
    path('plantas/', views.plantas, name='plantas'),
    path('plantas/categoria/<int:categoria_id>/', views.plantasPorCategoria, name='plantasPorCategoria'),
    path('plantas/crear/', views.crearPlanta, name='crearPlanta'),
    path('plantas/editar/<int:planta_id>/', views.editarPlanta, name='editarPlanta'),
    path('plantas/eliminar/<int:planta_id>/', views.eliminarPlanta, name='eliminarPlanta'),
    path('plantas/buscar/', views.buscarPlanta, name='buscarPlanta'),

    path('catalogoPlantas/', views.catalogoPlantas, name='catalogoPlantas'),
    path('catalogoPlantas/buscar/', views.catalogoBuscar, name='catalogoBuscar'),
    path('catalogoPlantas/categoria/<int:categoria_id>/', views.catalogoCategoria, name='catalogoCategoria'),

    path('subir-excel/', Vista_subir_excel.as_view(), name='subir_excel'),
]

Vivero/Sales/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Carrito
    path("cart/", views.cart_view, name="cart_view"),
    path("cart/add/<int:plant_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/remove/<int:item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path('cart/increase/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    # Pedidos
    path("register-sale/", views.register_sale, name="register_sale"),
    path("sales-history/", views.sales_history, name="sales_history"),
]

Vivero/Vivero/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import admin_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('authentication/', include('Authentication.urls')),
    path('sales/', include('Sales.urls')),
    path('inventory/', include('Inventory.urls')),
    path('admin/home/', admin_home, name='admin_home'),
]

Vivero/Inventory/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Categorie(models.Model):
    category_id = models.AutoField(primary_key=True, verbose_name="Id")
    category = models.CharField(max_length=30, verbose_name="Category")

    def __str__(self):
        return self.category
    
class Plant(models.Model):
    plant_id = models.AutoField(primary_key=True, verbose_name="Id")
    category_id = models.ForeignKey(Categorie, on_delete=models.CASCADE, verbose_name='Categorie')
    plant_name = models.CharField(max_length=30, verbose_name="Plant Name")
    care = models.CharField(max_length=1000, verbose_name="Care")
    price = models.IntegerField(validators=[MinValueValidator(0)], verbose_name="Price")
    stock = models.IntegerField(validators=[MinValueValidator(0)], verbose_name="Stock")

    def __str__(self):
        return self.plant_name

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    stock = models.IntegerField(default=0)
    stock_minimo = models.IntegerField(default=20)

    def en_stock_bajo(self):
        return self.stock <= self.stock_minimo

    def __str__(self):
        return f"{self.nombre} - Stock: {self.stock}"

Vivero/Inventory/views.py
import pandas as pd
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.core.files.storage import default_storage
from .models import Plant, Categorie
from Authentication.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator
from django.shortcuts import render

class Vista_subir_excel(View):
    def post(self, request):
        file = request.FILES.get('file')
        if not file:
            messages.error(request, 'No se ha subido ningún archivo')
            return redirect('plantas')

        # Guardar temporalmente el archivo
        file_path = default_storage.save(file.name, file)
        try:
            # Leer el archivo Excel
            df = pd.read_excel(file_path)

            for _, row in df.iterrows():
                category_name = row['category']
                plant_name = row['plant_name']
                care = row['care']
                price = row['price']
                stock = row['stock']

                # Buscar o crear la categoría
                category, _ = Categorie.objects.get_or_create(category=category_name)

                # Buscar la planta, si existe actualiza el stock, si no, créala
                plant, created = Plant.objects.get_or_create(
                    plant_name=plant_name,
                    category_id=category,
                    defaults={'care': care, 'price': price, 'stock': stock}
                )

                if not created:
                    plant.stock += stock  # Sumar stock existente
                    plant.save()
            verificar_stock(request)
            messages.success(request, 'Stock actualizado correctamente')
            return redirect('plantas')
        except Exception as e:
            messages.error(request, 'Error: Formato de archivo no permitido. Por favor, sube un archivo de Excel (.xls o .xlsx).')
            return redirect('plantas')

        finally:
            # Eliminar el archivo después de procesarlo
            if default_storage.exists(file_path):
                default_storage.delete(file_path)

        return redirect('plantas')

############## CRUD PLANTAS ##############
@staff_member_required(login_url='/')
@login_required
def plantas(request):
    plants_list = Plant.objects.all()
    categories = Categorie.objects.all()

    # Configurar paginación
    paginator = Paginator(plants_list, 10)  # 10 plantas por página
    page_number = request.GET.get('page')
    plants = paginator.get_page(page_number)

    verificar_stock(request)
    return render(request, 'CRUD Planta/plantas.html', {'plants': plants, 'categories': categories})

@staff_member_required(login_url='/')
@login_required
def plantasPorCategoria(request, categoria_id):
    categoria = get_object_or_404(Categorie, category_id=categoria_id)
    plants = Plant.objects.filter(category_id=categoria)
    categories = Categorie.objects.all()
    return render(request, 'CRUD Planta/plantas.html', {'categories': categories, 'plants': plants, 'categoria': categoria})

@staff_member_required(login_url='/')
@login_required
def editarPlanta(request, planta_id):
    plants = get_object_or_404(Plant, plant_id=planta_id)
    categories = Categorie.objects.all()
    
    if request.method == 'POST':
        plants.plant_name = request.POST.get('plant_name')
        plants.care = request.POST.get('care')
        plants.price = request.POST.get('price')
        plants.stock = request.POST.get('stock')
        
        category_id = request.POST.get('category') #Definir antes de usar
        if category_id:
            plants.category_id = get_object_or_404(Categorie, category_id=category_id)

        plants.save()
        messages.success(request, f'La planta "{plants.plant_name}" ha sido actualizado exitosamente.')
        verificar_stock(request)
        return redirect('plantas')
    
    return render(request, 'CRUD Planta/editarPlanta.html', {'plants': plants, 'categories': categories})

@staff_member_required(login_url='/')
@login_required
def crearPlanta(request):
    categories = Categorie.objects.all()
    
    if request.method == 'POST':
        plant_name = request.POST.get('plant_name', '').strip() #Elimina espacios extra
        care = request.POST.get('care' ,'').strip()
        price = request.POST.get('price', '').strip()
        stock = request.POST.get('stock', '0')
        category_id = request.POST.get('category')

        #Validaciones
        if not plant_name:
            messages.error(request, 'El nombre de la planta es obligatorio.')
            return render(request, 'CRUD Planta/crearPlanta.html', {'categories': categories})
    
        if category_id:  # Verificamos que category_id no sea None o vacío
            category = get_object_or_404(Categorie, category_id=category_id)  # Convertimos el ID en instancia
        else:
            messages.error(request, 'Debe seleccionar una categoría.')
            return render(request, 'CRUD Planta/crearPlanta.html', {'categories': categories})

        # Creamos la planta con la instancia correcta de Categorie
        plant = Plant(plant_name=plant_name, care=care, price=price, stock=stock, category_id=category)
        plant.save()
        messages.success(request, f'La planta "{plant.plant_name}" ha sido creado exitosamente.')
        verificar_stock(request)
        return redirect('plantas')
    
    return render(request, 'CRUD Planta/crearPlanta.html', {'categories': categories})

@staff_member_required(login_url='/')
@login_required
def eliminarPlanta(request, planta_id):
    plants = get_object_or_404(Plant, plant_id=planta_id)
    if request.method == 'POST':
        plants.delete()
        messages.success(request, f'La planta "{plants.plant_name}" ha sido eliminado exitosamente.')
        return redirect('plantas')
    return render(request, 'CRUD Planta/eliminarPlanta.html', {'plants': plants})

@staff_member_required(login_url='/')
@login_required
def buscarPlanta(request):
    query = request.GET.get('buscarPlanta', '').strip()
    plants = Plant.objects.filter(plant_name__icontains=query) if query else Plant.objects.all()
    categories = Categorie.objects.all()
    return render(request, 'CRUD Planta/plantas.html', {'plants': plants, 'categories': categories, 'query': query})

#######CATALOGO PLANTAS##########
#@login_required
def catalogoPlantas(request):
    plants_list = Plant.objects.all()
    categories = Categorie.objects.all()

    # Configurar paginación (mostrar 8 plantas por página)
    paginator = Paginator(plants_list, 8)  
    page_number = request.GET.get('page')
    plants = paginator.get_page(page_number)

    return render(request, 'Catalogo/catalogoPlantas.html', {
        'plants': plants,
        'categories': categories
    })

#@login_required
def catalogoCategoria(request, categoria_id):
    categoria = get_object_or_404(Categorie, category_id=categoria_id) 
    plants = Plant.objects.filter(category_id=categoria)
    categories = Categorie.objects.all()

    # Configurar paginación (mostrar 8 plantas por página)
    paginator = Paginator(plants, 8)  
    page_number = request.GET.get('page')
    plants = paginator.get_page(page_number)

    return render(request, 'Catalogo/catalogoPlantas.html', {
        'plants': plants,
        'categories': categories
    })

#@login_required
def catalogoBuscar(request):
    query = request.GET.get('buscarPlanta')
    plants = Plant.objects.filter(plant_name__icontains=query) if query else Plant.objects.all()
    categories = Categorie.objects.all()
    return render(request, 'Catalogo/catalogoPlantas.html', {'plants': plants, 'categories': categories})

############## STOCK BAJO ##############
def verificar_stock(request):
    plants = Plant.objects.all()
    for plant in plants:
        if plant.stock <= 5:
            messages.warning(request, f'!STOCK BAJO de {plant.plant_name}¡')

Vivero/Inventory/templates/CRUD Planta/crearPlanta.html
{% extends 'base.html' %}

{% block title %}Agregar{% endblock %}

{% load static %}

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center min-vh-120 px-3">
    <div class="card shadow-lg bg-white rounded-4 p-5 m-4 col-lg-6 col-md-8 col-sm-12" style="background-color:#f5f5dc;">
        <h2 class="text-center fw-bold mt-2 mb-4" style="color: #b58863;">Agregar Planta</h2>
        <hr class="border-1 opacity-75 mt-1">

        <form method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="plant_name" class="form-label">Nombre de la planta:</label>
                <input type="text" id="plant_name" name="plant_name" class="form-control" required style="border-color: rgb(255,179,71);">
            </div>

            <div class="mb-3">
                <label for="care" class="form-label">Recomendaciones de Cuidados:</label>
                <textarea id="care" name="care" class="form-control" rows="3" required style="border-color: rgb(255,179,71);"></textarea>
            </div>

            <div class="mb-3">
                <label for="id_price" class="form-label">Precio:</label>
                <input type="number" id="id_price" name="price" step="0.01" class="form-control" required style="border-color: rgb(255,179,71);">
            </div>

            <div class="mb-3">
                <label for="stock" class="form-label">Cantidad:</label>
                <input type="number" id="stock" name="stock" class="form-control" required style="border-color: rgb(255,179,71);">
            </div>

            <div class="mb-3">
                <label for="category" class="form-label">Categoría:</label>
                <div class="dropdown w-100">
                    <button type="button" class="btn dropdown-toggle w-100 text-start" style="background-color: rgb(255,179,71);" data-bs-toggle="dropdown" aria-expanded="false">
                        Selecciona una categoría
                    </button>
                    <ul class="dropdown-menu w-100">
                        {% for categoria in categories %}
                        <li>
                            <a class="dropdown-item" onclick="selectCategory('{{ categoria.category_id }}', '{{ categoria.category }}')">
                                {{ categoria.category }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <input type="hidden" name="category" id="selectedCategory">
            </div>

            <script>
                function selectCategory(id, name) {
                    document.querySelector('.dropdown button').textContent = name;
                    document.getElementById('selectedCategory').value = id;
                }
            </script>

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn shadow w-auto px-5 mt-3" style="background-color: rgb(107, 142, 35); color: white;">Agregar</button>
                <a href="{% url 'plantas' %}" class="btn shadow w-auto px-5 mt-3 ms-3" style="background-color: rgb(199, 86, 86); color: white;">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Vivero/Inventory/templates/CRUD Planta/editarPlanta.html
{% extends 'base.html' %}

{% block title %}Editar{% endblock %}

{% load static %}

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center min-vh-120 px-3">
    <div class="card shadow-lg bg-white rounded-4 p-5 m-4 col-lg-6 col-md-8 col-sm-12" style="background-color:#f5f5dc;">
        <h2 class="text-center fw-bold mt-2 mb-4" style="color: #b58863;">Editar Planta</h2>
        <hr class="border-1 opacity-75 mt-1">

        <form method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="plant_name" class="form-label">Nombre de la planta:</label>
                <input type="text" id="plant_name" name="plant_name" class="form-control" required style="border-color: rgb(255,179,71);" value="{{ plants.plant_name }}">
            </div>

            <div class="mb-3">
                <label for="care" class="form-label">Recomendaciones de Cuidados:</label>
                <textarea id="care" name="care" class="form-control" rows="3" required style="border-color: rgb(255,179,71);">{{ plants.care }}</textarea>
            </div>

            <div class="mb-3">
                <label for="id_price" class="form-label">Precio:</label>
                <input type="number" id="id_price" name="price" step="0.01" class="form-control" required style="border-color: rgb(255,179,71);" value="{{ plants.price }}">
            </div>

            <div class="mb-3">
                <label for="stock" class="form-label">Cantidad:</label>
                <input type="number" id="stock" name="stock" class="form-control" required style="border-color: rgb(255,179,71);" value="{{ plants.stock }}">
            </div>

            <div class="mb-3">
                <label for="category" class="form-label">Categoría:</label>
                <div class="dropdown w-100">
                    <button type="button" class="btn dropdown-toggle w-100 text-start" style="background-color: rgb(255,179,71);" data-bs-toggle="dropdown" aria-expanded="false">
                        {% if plants.category_id %}{{ plants.category_id.category }}
                        {% else %}
                        Selecciona una categoría
                        {% endif %}
                    </button>
                    <ul class="dropdown-menu w-100">
                        {% for categoria in categories %}
                        <li>
                            <a class="dropdown-item" onclick="selectCategory('{{ categoria.category_id }}', '{{ categoria.category }}')">
                                {{ categoria.category }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <input type="hidden" name="category" id="selectedCategory" value="{{ plants.category_id.category_id }}">
            </div>

            <script>
                function selectCategory(id, name) {
                    document.querySelector('.dropdown button').textContent = name;
                    document.getElementById('selectedCategory').value = id;
                }
            </script>

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn shadow w-auto px-5 mt-3" style="background-color: rgb(107, 142, 35); color: white;">Guardar cambios</button>
                <a href="{% url 'plantas' %}" class="btn shadow w-auto px-5 mt-3 ms-3" style="background-color: rgb(199, 86, 86); color: white;">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Vivero/Inventory/templates/CRUD Planta/eliminarPlanta.html
{% extends 'base.html' %}

{% block title %}Eliminar Planta{% endblock %}

{% block content %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap JS (necesario para dropdowns) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<div class="container-fluid d-flex justify-content-center align-items-center min-vh-120 px-3" style="background-color:#f5f5dc;">
    <div class="card shadow-lg bg-white rounded-4 p-4 m-4 col-lg-5 col-md-8 col-sm-10 text-center">
        <h2 class="text-center fw-bold mb-4" style="color: #b58863;">Eliminar Planta</h2>
        <hr class="border-1 opacity-75" style="color:  rgb(107, 142, 35);">
        
        <p class="fs-5 text-dark">¿Estás seguro de que deseas eliminar la planta <strong>"{{ plants.plant_name }}"</strong>?</p>
        
        <form method="post">
            {% csrf_token %}
            <div class="d-flex justify-content-center flex-wrap mt-4">
                <button type="submit" class="btn px-4 mx-2 text-white" style="background-color: #d9534f;">Eliminar</button>
                <a href="{% url 'plantas' %}" class="btn px-4 mx-2 text-white" style="background-color:  rgb(107, 142, 35);">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Vivero/Inventory/templates/CRUD Planta/plantas.html
{% extends 'base.html' %}

{% block title %}Inventario{% endblock %}

<!--Carga instruccion bloque js-->
{% load static %}

{% block content %}
<!-- Bootstrap JS (necesario para dropdowns) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<div class="container-fluid d-flex justify-content-center align-items-center min-vh-100 px-3">
    <div class="card shadow-lg bg-white rounded-4 p-4 m-4 col-lg-11 col-md-10 col-sm-12"
        style="background-color:#f5f5dc;">
        <h2 class="text-center fw-bold mt-2 mb-4" style="color: #b58863;">Gestión de Inventario</h2>
        <hr class="border-1 opacity-75 mt-1">

        <!-- Notificaciones -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}

        <!-- Filtros -->
        <div class="row mb-3 align-items-center">
            <div class="col-md-6">
                <form method="GET" action="{% url 'buscarPlanta' %}">
                    <input type="text" class="form-control" style="border-color: rgb(255,179,71);" name="buscarPlanta"
                        placeholder="Buscar plantas..." value="{{ query|default:'' }}">
                </form>
            </div>

            <div class="col-md-4 mt-2">
                <div class="dropdown w-100">
                    <button type="button" class="btn dropdown-toggle w-100 text-start"
                        style="background-color: rgb(255,179,71);" data-bs-toggle="dropdown" aria-expanded="false"
                        id="categoryDropdown">
                        {% if categoria %}
                        {{ categoria.category }}
                        {% else %}
                        Selecciona una categoría
                        {% endif %}
                    </button>
                    <ul class="dropdown-menu w-100">
                        <li>
                            <a class="dropdown-item" href="{% url 'plantas' %}">Todas las categorías</a>
                        </li>
                        {% for categoria_item in categories %}
                        <li>
                            <a class="dropdown-item" href="{% url 'plantasPorCategoria' categoria_item.category_id %}">
                                {{ categoria_item.category }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="d-flex justify-content-between align-items-center me-2 mt-2">
                <!-- Botón Agregar (Izquierda) -->
                <div class="col-md-2 text-start">
                    <a href="{% url 'crearPlanta' %}" class="btn shadow align-items-center justify-content-center"
                        style="background-color: rgb(107, 142, 35); color: white;"> 
                        <ion-icon name="add-sharp"></ion-icon> Agregar 
                    </a>
                </div>
            
                <!-- Botón Popup: Subir Archivo (Derecha) -->
                <div class="text-end">
                    <button type="button" class="btn shadow align-items-center justify-content-center" data-bs-toggle="modal" data-bs-target="#uploadModal"
                        style="background-color: rgb(107, 142, 35); color: white;">
                        <ion-icon name="arrow-up-sharp"></ion-icon> Subir Archivo
                    </button>
                </div>
            </div>
            

            <!-- Modal -->
            <div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="uploadModalLabel">Subir Archivo</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Cerrar"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{% url 'subir_excel' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <input type="file" name="file" class="form-control">
                                </div>
                                <button type="submit" class="btn btn-warning">Subir</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="border-1 opacity-75 mt-1 mb-3">

        <!-- Tabla de Plantas -->
        <div class="table-responsive">
            <table class="table table-hover rounded-3 overflow-hidden">
                <thead class="text-white" style="background-color: rgb(107, 142, 35);">
                    <tr>
                        <th class="align-middle" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Id</th>
                        <th class="align-middle" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Categoria</th>
                        <th class="align-middle" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Nombre</th>
                        <th class="align-middle" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Recomendaciones de cuidados</th>
                        <th class="align-middle" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Precio</th>
                        <th class="align-middle text-center" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Cantidad</th>
                        <th class="text-center" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px; background-color: rgb(107, 142, 35); color: white;">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for planta in plants %}
                    <tr>
                        <td class="align-middle">{{ planta.plant_id}}</td>
                        <td class="align-middle">{{ planta.category_id}}</td>
                        <td class="align-middle">{{ planta.plant_name}}</td>
                        <td class="align-middle">{{ planta.care }}</td>
                        <td class="align-middle">${{ planta.price }}</td>
                        <td class="align-middle text-center">{{ planta.stock }}</td>
                        <td class="text-center align-middle">
                            <div class="d-flex flex-wrap justify-content-center gap-2">
                                <a href="{% url 'editarPlanta' planta.plant_id %}" class="btn btn-sm shadow-sm"
                                    style="background-color: #b58863; color: white;">Editar</a>
                                <a href="{% url 'eliminarPlanta' planta.plant_id %}" class="btn btn-sm shadow-sm"
                                    style="background-color: #b58863; color: white;">Eliminar</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- Paginación -->
        <div class="d-flex justify-content-center mt-3">
            <nav>
                <ul class="pagination">
                    {% if plants.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" style="background-color: #b58863; color: white;">&laquo;
                            Primera</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ plants.previous_page_number }}"
                            style="background-color: #b58863; color: white;">Anterior</a>
                    </li>
                    {% endif %}

                    <li class="page-item disabled">
                        <span class="page-link">Página {{ plants.number }} de {{ plants.paginator.num_pages }}</span>
                    </li>

                    {% if plants.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ plants.next_page_number }}"
                            style="background-color: #b58863; color: white;">Siguiente</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ plants.paginator.num_pages }}"
                            style="background-color: #b58863; color: white;">Última &raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var dropdownButton = document.getElementById("categoryDropdown");
        var dropdownMenu = document.querySelector(".dropdown-menu");

        dropdownButton.addEventListener("click", function () {
            var dropdown = new bootstrap.Dropdown(dropdownButton);
            dropdown.toggle();
        });

        // Cierra el dropdown si el usuario hace clic fuera de él
        document.addEventListener("click", function (event) {
            if (!dropdownButton.contains(event.target) && !dropdownMenu.contains(event.target)) {
                var openDropdown = bootstrap.Dropdown.getInstance(dropdownButton);
                if (openDropdown) {
                    openDropdown.hide();
                }
            }
        });
    });
</script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
{%endblock%}